services:
  worker-scraping-browser:
    container_name: worker-scraping-browser-${SESSION}
    restart: always

    build:
      context: ./
      dockerfile: ./Dockerfile

    environment:
      # - PRISMA_URI=${PRISMA_URI}
      - SESSION=${SESSION}
      - PROXY_URI=${PROXY_URI}
      - MONGO_URI=${MONGO_URI}
      - TZ=${TZ}
      - SERVER=${SERVER}
      - HATCHET_CLIENT_TOKEN=${HATCHET_CLIENT_TOKEN}
      - HATCHET_CLIENT_TLS_STRATEGY=${HATCHET_CLIENT_TLS_STRATEGY}

    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_URI}
        tag: worker-scraping-browser
        labels: "server=${SERVER},SESSION=${SESSION}"
        mode: non-blocking
        max-buffer-size: 1k
