services:
  worker-scraping-browser:
    container_name: worker-scraping-browser-${SESSION}
    restart: always

    build:
      context: ./
      dockerfile: ./Dockerfile

    volumes:
      - /home/dima/scrape_sessions/${SERVER}_${SESSION}:/app/profileDir
      - /home/dima/extensions:/app/extensions:ro

    environment:
      - PLAYWRIGHT_FIREFOX_POLICIES_JSON=/app/policies.json
      - LABELS=${LABELS}
      - PRISMA_URI=${PRISMA_URI}
      - SESSION=${SESSION}
      - PROXY_URI=${PROXY_URI}
      - MONGO_URI=${MONGO_URI}
      - HATCHET_CLIENT_TOKEN=${HATCHET_CLIENT_TOKEN}
      - HATCHET_CLIENT_TLS_STRATEGY=${HATCHET_CLIENT_TLS_STRATEGY}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_COVERS_BUCKET=${AWS_COVERS_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TZ=${TZ}
      - SERVER=${SERVER}

    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_URI}
        tag: worker-scraping-browser
        labels: "server=${SERVER},SESSION=${SESSION}"
        mode: non-blocking
        max-buffer-size: 1k
